<?xml version="1.0" encoding="UTF-8" ?>
<testsuite errors="0" failures="0" hostname="grails" name="FederatedRealmSpec" tests="8" time="0.607" timestamp="2011-08-31T06:41:10">
  <properties />
  <testcase classname="FederatedRealmSpec" name="UnknownAccountException when federated authentication is not enabled" time="0.03" />
  <testcase classname="FederatedRealmSpec" name="UnknownAccountException when principal is not supplied" time="0.02" />
  <testcase classname="FederatedRealmSpec" name="UnknownAccountException when credential is not supplied" time="0.018" />
  <testcase classname="FederatedRealmSpec" name="DisabledAccountException when user doesnt already exist and autoprovision disabled" time="0.077" />
  <testcase classname="FederatedRealmSpec" name="Basic account created when autoprovision is enabled" time="0.111" />
  <testcase classname="FederatedRealmSpec" name="Existing, disabled account throws DisabledAccountException" time="0.087" />
  <testcase classname="FederatedRealmSpec" name="Failing subject save for new account throws RuntimeException" time="0.101" />
  <testcase classname="FederatedRealmSpec" name="Failing subject save for session record throws RuntimeException" time="0.157" />
  <system-out><![CDATA[--Output from UnknownAccountException when federated authentication is not enabled--
ERROR (FederatedRealm): Authentication attempt for federated provider, denying attempt as federation integration disabled
--Output from UnknownAccountException when principal is not supplied--
ERROR (FederatedRealm): Authentication attempt for federated provider, denying attempt as no persistent identifier was provided
--Output from UnknownAccountException when credential is not supplied--
ERROR (FederatedRealm): Authentication attempt for federated provider, denying attempt as no credential was provided
--Output from DisabledAccountException when user doesnt already exist and autoprovision disabled--
ERROR (FederatedRealm): Authentication attempt for federated provider, denying attempt as federation integration is denying automated account provisioning
--Output from Basic account created when autoprovision is enabled--
INFO (FederatedRealm): No subject represented by http://test.com!http://sp.test.com!1234 exists in local repository, provisioning new account
INFO (FederatedRealm): Successfully logged in subject [2]http://test.com!http://sp.test.com!1234 using federated source
--Output from Existing, disabled account throws DisabledAccountException--
WARN (FederatedRealm): Attempt to authenticate using using federated principal mapped to a locally disabled account [3]http://test.com!http://sp.test.com!1234
--Output from Failing subject save for new account throws RuntimeException--
INFO (FederatedRealm): No subject represented by http://test.com!http://sp.test.com!1234 exists in local repository, provisioning new account
ERROR (FederatedRealm): org.codehaus.groovy.grails.plugins.testing.GrailsMockErrors: 0 errors
--Output from Failing subject save for session record throws RuntimeException--
ERROR (FederatedRealm): org.codehaus.groovy.grails.plugins.testing.GrailsMockErrors: 0 errors
]]></system-out>
  <system-err><![CDATA[--Output from UnknownAccountException when federated authentication is not enabled--
--Output from UnknownAccountException when principal is not supplied--
--Output from UnknownAccountException when credential is not supplied--
--Output from DisabledAccountException when user doesnt already exist and autoprovision disabled--
--Output from Basic account created when autoprovision is enabled--
--Output from Existing, disabled account throws DisabledAccountException--
--Output from Failing subject save for new account throws RuntimeException--
--Output from Failing subject save for session record throws RuntimeException--
]]></system-err>
</testsuite>
